apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Create hello world file
        shell: sh
        run: |
          echo $PWD
          echo "Hello world" > check.txt
          cat check.txt
          ls -al
          
      - uses: docker://golang:1.20.3-alpine3.17
        name: check the file
        shell: sh
        run: |
          echo $PWD
          ls -al
          cat check.txt
          ls -al
