apiVersion: automation.cloudbees.io/v1alpha1

kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout Repository
        uses: cloudbees-io/checkout@v1
      - run: |
          git log -n 1 --format="%H"
          echo "$(git log -n 1 --format="%H")" > "$CLOUDBEES_OUTPUTS/id"
        uses: docker://alpine/git:latest
        id: sha
      - name: Publish workflow evidence item
        uses: cloudbees-io/publish-evidence-item@v1
        if: ${{always()}}
        with:
          content: |
            ${{steps.sha.outputs.id}}

